name: Build Game and Server
on: [workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-2022
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        shell: cmd
        run: |
          cd src
          git clone --depth=1 https://github.com/ko4life-net/ko-vendor.git vendor

      - name: Build KnightOnLine
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild Game.sln -t:Clean -t:Build -p:Configuration=Release /m

      - name: Build Server
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild Server.sln -t:Clean -t:Build -p:Configuration=Release /m

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: x86-release
          path: src/build/Release/*.exe
