name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: cmd
        run: |
          build.cmd

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: All-x86-release
          path: src/build/Release/*.exe
